---
title: "Gender patterns in reporting over time"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(openfda)
library(here)
load(here::here('data/freqs.rda'))
yrs = seq(2004, 2020)

# indications <- fda_query('/drug/event.json') %>% 
#   fda_api_key(readLines(here('Personal','apikey.txt'))) %>% 
#   fda_filter('receivedate', '[20190101+TO+20191231]') %>% 
#   fda_count('patient.drug.drugindication.exact') %>% 
#   fda_limit(20) %>% 
#   fda_exec() %>% 
#   mutate(term = str_to_lower(term))
```

Column {.sidebar}
-----------------------------------------------------------------------

### Top 20 Indications (2019)

```{r}
selectInput('indication', label='Indication', choices = freq_indications$term, selected='hypertension')
```

Column
-----------------------------------------------------------------------

```{r}
get_freqs <- function(filt){
   map(yrs,
                  ~{Sys.sleep(0.2);
                    fda_query('/drug/event.json') %>% 
                    fda_filter('receivedate', paste0('[', .x, '0101+TO+',.x,'1231]')) %>% 
                    fda_filter('patient.drug.drugindication',str_replace_all(filt, ' ', '+')) %>% 
                    fda_count('patient.patientsex') %>% 
                    fda_limit(1000) %>% fda_exec() %>% set_names(c('term',paste('count', .x, sep='_')))})
freq_gender <- reduce(freq_gender, full_join) %>% 
  gather(yr, counts, -term) %>% 
  mutate(yr = as.numeric(str_remove(yr, 'count_')))
return(freq_gender)
}
freq_gender <-renderPlot({
    ggplot(get_freqs(input$indication), aes(x = yr, y = counts, fill = term)) + geom_bar(stat='identity', position = 'fill')
})

renderText({input$indication})
```

